@startuml
left to right direction
actor ユーザー
actor 管理会社
rectangle ショッピングサイト{
	ユーザー --> (ログインする)
	ユーザー --> (ログアウトする)
	ユーザー --> (サイトを見る)
	ユーザー --> (商品を検索する)
	ユーザー --> (サンプルを見る)
	ユーザー --> (サイズを選ぶ)
	ユーザー --> (商品を買う)

	(ログインする)<--管理会社
	(ログアウトする)<--管理会社
	(サイトを見る)<--管理会社
	(サンプルを見る)<--管理会社
	(サイズを選ぶ)<--管理会社
	(商品を買う)<--管理会社
	(商品を追加する)<--管理会社
	(商品を削除する)<--管理会社
	(発注伝票を見る)<--管理会社

}
	(発送する)<--管理会社
@enduml